<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'nik' => '1111111111110001',
                'name' => 'Admin DPC',
                'gelar_depan' => null,
                'gelar_belakang' => null,
                'email' => 'admin@example.com',
                'password' => Hash::make('password'),
                'foto_ktp' => null,
                'nomor_kta' => null,
                'foto_kta' => null,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'usia' => null,
                'jenis_kelamin' => null,
                'agama' => null,
                'status_perkawinan' => null,
                'alamat_ktp' => null,
                'rt' => null,
                'rw' => null,
                'kecamatan' => null,
                'kelurahan_desa' => null,
                'kabupaten' => 'Bengkalis',
                'foto_profil' => null,
                'dapil' => null,
                'jumlah_suara' => 0,
                'jumlah_suara_sebelumnya' => 0,
                'jumlah_tim' => 0,
                'role' => 'admin',
                'email_verified_at' => now(),
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '1111111111110002',
                'name' => 'H. Ketua DPC',
                'gelar_depan' => 'H.',
                'gelar_belakang' => 'S.E',
                'email' => 'ketua@example.com',
                'password' => Hash::make('password'),
                'foto_ktp' => 'ktp/ktpketua.jpg',
                'nomor_kta' => 'KTA-002-2025',
                'foto_kta' => 'kta/ktaketua.jpg',
                'tempat_lahir' => 'Bengkalis',
                'tanggal_lahir' => '1982-04-10',
                'usia' => 43,
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'status_perkawinan' => 'Menikah',
                'alamat_ktp' => 'Jl. Merdeka No.10',
                'rt' => '03',
                'rw' => '02',
                'kecamatan' => 'Mandau',
                'kelurahan_desa' => 'Air Jamban',
                'kabupaten' => 'Bengkalis',
                'foto_profil' => 'profil/profileketua.jpg',
                'dapil' => 'Dapil 1',
                'jumlah_suara' => 220,
                'jumlah_suara_sebelumnya' => 200,
                'jumlah_tim' => 5,
                'role' => 'ketua',
                'email_verified_at' => now(),
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '1111111111110003',
                'name' => 'M. Andika',
                'gelar_depan' => null,
                'gelar_belakang' => null,
                'email' => 'user@example.com',
                'password' => Hash::make('password'),
                'foto_ktp' => 'ktp/ktpuser1.jpg',
                'nomor_kta' => 'KTA-003-2025',
                'foto_kta' => 'kta/ktauser1.jpg',
                'tempat_lahir' => 'Bantan',
                'tanggal_lahir' => '1995-06-01',
                'usia' => 30,
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Menikah',
                'alamat_ktp' => 'Jl. Pendidikan No. 12',
                'rt' => '01',
                'rw' => '04',
                'kecamatan' => 'Bantan',
                'kelurahan_desa' => 'Selatbaru',
                'kabupaten' => 'Bengkalis',
                'foto_profil' => 'profil/profileuser1.jpg',
                'dapil' => 'Dapil 2',
                'jumlah_suara' => 80,
                'jumlah_suara_sebelumnya' => 65,
                'jumlah_tim' => 3,
                'role' => 'user',
                'email_verified_at' => now(),
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
